# Generated by Django 3.2.6 on 2023-02-20 13:03

from django.conf import settings
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenedURL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('long_url', models.TextField()),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('assigned_users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shortened URL',
                'verbose_name_plural': 'Shortened URLs',
                'ordering': ('-created',),
            },
        ),
        migrations.AddIndex(
            model_name='shortenedurl',
            index=models.Index(fields=['id'], name='url_app_sho_id_fe31f2_idx'),
        ),
    ]
