# Generated by Django 3.2.6 on 2023-02-21 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('url_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shortenedurl',
            name='assigned_users',
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='assigned_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shortenedurl',
            name='short_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
