# Generated by Django 3.2.6 on 2025-05-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_app', '0002_auto_20230221_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
