# Generated by Django 3.2.6 on 2023-02-20 11:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=16, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=16, null=True)),
                ('last_name', models.CharField(blank=True, max_length=16, null=True)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Please enter a valid email address.')])),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Please enter a valid phone number.', regex=re.compile('^[6-9]{1}[0-9]{9}$'))])),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=32, null=True)),
                ('user_slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('unsuccessful_login_attempts', models.PositiveIntegerField(blank=True, default=0, help_text='Number of unsuccessful login attempts', null=True)),
                ('blocked_until', models.DateTimeField(blank=True, help_text='Blocked until', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-date_joined', 'id'),
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoneEditToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
                ('new_phone', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Please enter a valid phone number.', regex=re.compile('^[6-9]{1}[0-9]{9}$'))])),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Phone Edit Token',
                'verbose_name_plural': 'User Phone Edit Tokens',
                'ordering': ('user', '-created'),
            },
        ),
        migrations.CreateModel(
            name='UserPasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Password Reset Token',
                'verbose_name_plural': 'User Password Reset Tokens',
                'ordering': ('user', '-created'),
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('otp', models.CharField(max_length=256)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User OTP',
                'verbose_name_plural': 'User OTPs',
                'ordering': ('-created', 'id'),
            },
        ),
        migrations.CreateModel(
            name='UserEmailEditToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(max_length=256)),
                ('new_email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(code='invalid_email', message='Please enter a valid email address.')])),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Email Edit Token',
                'verbose_name_plural': 'User Email Edit Tokens',
                'ordering': ('user', '-created'),
            },
        ),
        migrations.AddIndex(
            model_name='userphoneedittoken',
            index=models.Index(fields=['id'], name='user_app_us_id_ca6a78_idx'),
        ),
        migrations.AddIndex(
            model_name='userphoneedittoken',
            index=models.Index(fields=['user'], name='user_app_us_user_id_563085_idx'),
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['id'], name='user_app_us_id_678499_idx'),
        ),
        migrations.AddIndex(
            model_name='userpasswordresettoken',
            index=models.Index(fields=['user'], name='user_app_us_user_id_bd48da_idx'),
        ),
        migrations.AddIndex(
            model_name='userotp',
            index=models.Index(fields=['id'], name='user_app_us_id_b83c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='useremailedittoken',
            index=models.Index(fields=['id'], name='user_app_us_id_376b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='useremailedittoken',
            index=models.Index(fields=['user'], name='user_app_us_user_id_406262_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['id'], name='user_app_us_id_27d14b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='user_app_us_usernam_f18b04_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='user_app_us_email_eb2b78_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='user_app_us_phone_93d6c1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_slug'], name='user_app_us_user_sl_2451e7_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['first_name', 'last_name'], name='user_app_us_first_n_36f7f5_idx'),
        ),
    ]
